# Generated by Django 5.0.3 on 2025-07-26 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacions',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
